# Generated by Django 6.0 on 2026-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage to apply on bills', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='gstin_number',
            field=models.CharField(blank=True, help_text='GST Identification Number', max_length=15, null=True),
        ),
    ]
