# Generated by Django 6.0 on 2026-01-11 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_gst_percentage_user_gstin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_key', models.CharField(choices=[('trial', 'Trial Plan'), ('1month', '1 Month Plan'), ('3months', '3 Months Plan'), ('6months', '6 Months Plan'), ('12months', '12 Months Plan')], help_text='Unique plan identifier', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Plan display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Plan description', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Plan price', max_digits=10)),
                ('billing_requests', models.IntegerField(default=0, help_text='Number of billing requests (0 = unlimited)')),
                ('duration_days', models.IntegerField(help_text='Plan duration in days')),
                ('has_unlimited_bills', models.BooleanField(default=False, help_text='Unlimited bill creation')),
                ('has_cloud_storage', models.BooleanField(default=True, help_text='Cloud storage enabled')),
                ('has_gst_compliance', models.BooleanField(default=True, help_text='GST compliance enabled')),
                ('has_multi_device', models.BooleanField(default=True, help_text='Multi-device access')),
                ('has_cloud_backup', models.BooleanField(default=False, help_text='Cloud backup enabled')),
                ('has_24x7_support', models.BooleanField(default=False, help_text='24/7 customer support')),
                ('has_inventory_management', models.BooleanField(default=False, help_text='Inventory management enabled')),
                ('has_insights_dashboard', models.BooleanField(default=False, help_text='Insights dashboard enabled')),
                ('has_sales_reports', models.BooleanField(default=False, help_text='Sales reports enabled')),
                ('has_inventory_reports', models.BooleanField(default=False, help_text='Inventory reports enabled')),
                ('has_excel_export', models.BooleanField(default=False, help_text='Excel export enabled')),
                ('is_active', models.BooleanField(default=True, help_text='Plan is active and available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_requests_remaining',
            field=models.IntegerField(default=0, help_text='Number of billing requests remaining (used for plans with limits)'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_plan',
            field=models.ForeignKey(blank=True, help_text='Current active plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.plan'),
        ),
    ]
