# Generated by Django 6.0 on 2026-01-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_assign_trial_to_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account_activated',
            field=models.BooleanField(default=False, help_text='Account activated by admin after payment verification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='User can log in'),
        ),
    ]
