# Generated by Django 6.0 on 2026-01-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_business_address_user_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Name of person who referred this user', max_length=200, null=True),
        ),
    ]
