# Generated by Django 6.0 on 2026-01-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for digital payments', max_length=100, null=True),
        ),
    ]
