# Generated by Django 6.0 on 2026-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Custom plan - not shown in public plan list'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_key',
            field=models.CharField(help_text='Unique plan identifier', max_length=50, unique=True),
        ),
    ]
