# Generated by Django 6.0 on 2026-01-09 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='completed', help_text='Bill status: pending or completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'status'], name='bill_bill_user_id_16d9a3_idx'),
        ),
    ]
