# Generated by Django 6.0 on 2026-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_status_bill_bill_bill_user_id_16d9a3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CGST amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SGST amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before GST', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount including GST', max_digits=10),
        ),
    ]
