# Generated by Django 6.0 on 2026-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_bill_cgst_amount_bill_sgst_amount_bill_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Available stock quantity', max_digits=10, null=True),
        ),
    ]
