# Generated by Django 6.0 on 2026-01-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
