# Generated by Django 6.0 on 2026-01-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='manage_inventory',
            field=models.BooleanField(default=False, help_text='Whether to track inventory for this product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available stock quantity', max_digits=10),
        ),
    ]
