# Generated by Django 6.0 on 2026-01-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_remove_product_description_product_manage_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Payment status: True if paid, False if unpaid'),
        ),
    ]
