# Generated by Django 6.0 on 2026-01-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_bill_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Payment status: True if paid, False if unpaid (default unpaid for new bills)'),
        ),
    ]
