# Generated by Django 6.0 on 2026-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_alter_bill_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Payment status: True if paid, False if unpaid'),
        ),
    ]
